before_script:
  - docker info
  - cat /etc/hosts
  - export PYTHONIOENCODING=utf-8
after_script:
  # We need to clean up any files that Toil may have made via Docker that
  # aren't deletable by the Gitlab user. If we don't do this, Gitlab will try
  # and clean them up before running the next job on the runner, fail, and fail
  # that next job.
  - pwd
  - sudo rm -rf tmp


stages:
#  - main_tests
#  - test
  - integration


# Python3.6

#main:
#  stage: main_tests
#  script:
#    - pwd
#    - virtualenv -p python3.6 venv && . venv/bin/activate && make prepare && make develop extras=[all] && pip install htcondor
#    - python -m pytest src/toil/test/src
#    - python -m pytest src/toil/test/utils
#
#batch_systems:
#  stage: test
#  script:
#    - pwd
#    - virtualenv -p python3.6 venv && . venv/bin/activate && make prepare && make develop extras=[all] && pip install htcondor
#    - python -m pytest src/toil/test/batchSystems/batchSystemTest.py
#    - python -m pytest src/toil/test/mesos/MesosDataStructuresTest.py
#
#cwl:
#  stage: test
#  script:
#    - pwd
#    - virtualenv -p python3.6 venv && . venv/bin/activate && make prepare && make develop extras=[all] && pip install htcondor
#    - python -m pytest src/toil/test/cwl/cwlTest.py
#
#wdl:
#  stage: test
#  script:
#    - pwd
#    - virtualenv -p python3.6 venv && . venv/bin/activate && make prepare && make develop extras=[all] && pip install htcondor
#    - python -m pytest src/toil/test/wdl/toilwdlTest.py
#
#sort_and_jobstore:
#  stage: test
#  script:
#    - pwd
#    - virtualenv -p python3.6 venv && . venv/bin/activate && make prepare && make develop extras=[all] && pip install htcondor
#    - python -m pytest src/toil/test/jobStores/jobStoreTest.py  # delete and only run with integration=True?
#    - python -m pytest src/toil/test/sort/sortTest.py
#    - python -m pytest src/toil/test/provisioners/clusterScalerTest.py
#
#jobstore_integration:
#  stage: integration
#  script:
#    - pwd
#    - apt update && DEBIAN_FRONTEND=noninteractive apt install -y tzdata && apt install -y awscli jq
#    - virtualenv -p python3.6 venv && . venv/bin/activate && make prepare && make develop extras=[all] && pip install htcondor awscli
#    - export TOIL_TEST_INTEGRATIVE=True
#    - export TOIL_AWS_KEYNAME=id_rsa
#    - export TOIL_AWS_ZONE=us-west-2a
#    - python setup_gitlab_ssh.py
#    - mkdir ~/.aws
#    - echo -e $(aws secretsmanager get-secret-value --secret-id allspark/runner/credentials --region us-west-2 | jq -r .SecretString) > ~/.aws/credentials
#    - python -m pytest src/toil/test/jobStores/jobStoreTest.py

provisioner_integration:
  stage: integration
  script:
    - pwd
    - apt update && DEBIAN_FRONTEND=noninteractive apt install -y tzdata awscli jq
    - virtualenv -p python3.6 --system-site-packages --never-download venv && . venv/bin/activate && make prepare && make develop extras=[all] && pip install htcondor && pip install awscli==1.16.278
    - export TOIL_TEST_INTEGRATIVE=True; export TOIL_AWS_KEYNAME=id_rsa; export TOIL_AWS_ZONE=us-west-2a
    - python setup_gitlab_ssh.py
    - chmod 400 /root/.ssh/id_rsa
    - export LIBPROCESS_IP=127.0.0.1
    - mkdir ~/.aws
    - python setup_gitlab_docker.py
    - echo -e $(aws secretsmanager get-secret-value --secret-id allspark/runner/credentials --region us-west-2 | jq -r .SecretString) > ~/.aws/credentials
    - export TOIL_APPLIANCE_SELF=quay.io/ucsc_cgl/toil:$(python version_template.py dockerTag)
    - echo $TOIL_APPLIANCE_SELF
    - make push_docker
    - python -m pytest -s src/toil/test/provisioners/aws/awsProvisionerTest.py::AWSRestartTest::testAutoScaledCluster
    # - python -m pytest -s src/toil/test/provisioners/aws/awsProvisionerTest.py
    # - python -m pytest -s src/toil/test/provisioners/gceProvisionerTest.py  # needs env vars set to run
