language: python
python:
  - "3.6"
install:
  - pip install -U pip
  - make prepare
  - make develop extras=[aws,google,wdl] # adding extras to avoid import errors
script:
  - TOIL_TEST_QUICK=True make test_offline
